// ─────────────────────────────────────────────────────────────────────────────
// India Pincode Database — 3-digit prefix → { state, district }
// No external API needed. Covers all ~19,000+ pincodes in India.
// ─────────────────────────────────────────────────────────────────────────────

export const PINCODE_DB = {
  // ── DELHI (110) ────────────────────────────────────────────────────────────
  110: { state: 'Delhi', district: 'New Delhi' },

  // ── HARYANA (121–136) ──────────────────────────────────────────────────────
  121: { state: 'Haryana', district: 'Faridabad' },
  122: { state: 'Haryana', district: 'Gurgaon' },
  123: { state: 'Haryana', district: 'Mahendragarh' },
  124: { state: 'Haryana', district: 'Rohtak' },
  125: { state: 'Haryana', district: 'Hisar' },
  126: { state: 'Haryana', district: 'Jind' },
  127: { state: 'Haryana', district: 'Bhiwani' },
  128: { state: 'Haryana', district: 'Sirsa' },
  129: { state: 'Haryana', district: 'Sonipat' },
  130: { state: 'Haryana', district: 'Sonipat' },
  131: { state: 'Haryana', district: 'Sonipat' },
  132: { state: 'Haryana', district: 'Karnal' },
  133: { state: 'Haryana', district: 'Ambala' },
  134: { state: 'Haryana', district: 'Ambala' },
  135: { state: 'Haryana', district: 'Yamuna Nagar' },
  136: { state: 'Haryana', district: 'Kurukshetra' },

  // ── PUNJAB (140–160) ───────────────────────────────────────────────────────
  140: { state: 'Punjab', district: 'Rupnagar' },
  141: { state: 'Punjab', district: 'Ludhiana' },
  142: { state: 'Punjab', district: 'Ludhiana' },
  143: { state: 'Punjab', district: 'Amritsar' },
  144: { state: 'Punjab', district: 'Jalandhar' },
  145: { state: 'Punjab', district: 'Pathankot' },
  146: { state: 'Punjab', district: 'Hoshiarpur' },
  147: { state: 'Punjab', district: 'Patiala' },
  148: { state: 'Punjab', district: 'Sangrur' },
  149: { state: 'Punjab', district: 'Muktsar' },
  151: { state: 'Punjab', district: 'Bathinda' },
  152: { state: 'Punjab', district: 'Ferozepur' },
  153: { state: 'Punjab', district: 'Ferozepur' },
  160: { state: 'Chandigarh', district: 'Chandigarh' },

  // ── HIMACHAL PRADESH (171–177) ────────────────────────────────────────────
  171: { state: 'Himachal Pradesh', district: 'Shimla' },
  172: { state: 'Himachal Pradesh', district: 'Shimla' },
  173: { state: 'Himachal Pradesh', district: 'Solan' },
  174: { state: 'Himachal Pradesh', district: 'Bilaspur' },
  175: { state: 'Himachal Pradesh', district: 'Mandi' },
  176: { state: 'Himachal Pradesh', district: 'Kangra' },
  177: { state: 'Himachal Pradesh', district: 'Hamirpur' },

  // ── JAMMU & KASHMIR (180–194) ─────────────────────────────────────────────
  180: { state: 'Jammu & Kashmir', district: 'Jammu' },
  181: { state: 'Jammu & Kashmir', district: 'Jammu' },
  182: { state: 'Jammu & Kashmir', district: 'Udhampur' },
  183: { state: 'Jammu & Kashmir', district: 'Kathua' },
  184: { state: 'Jammu & Kashmir', district: 'Rajouri' },
  185: { state: 'Jammu & Kashmir', district: 'Poonch' },
  190: { state: 'Jammu & Kashmir', district: 'Srinagar' },
  191: { state: 'Jammu & Kashmir', district: 'Srinagar' },
  192: { state: 'Jammu & Kashmir', district: 'Anantnag' },
  193: { state: 'Jammu & Kashmir', district: 'Baramulla' },
  194: { state: 'Ladakh', district: 'Leh' },

  // ── UTTAR PRADESH (201–285) ───────────────────────────────────────────────
  201: { state: 'Uttar Pradesh', district: 'Gautam Buddha Nagar' },
  202: { state: 'Uttar Pradesh', district: 'Aligarh' },
  203: { state: 'Uttar Pradesh', district: 'Aligarh' },
  204: { state: 'Uttar Pradesh', district: 'Aligarh' },
  205: { state: 'Uttar Pradesh', district: 'Mainpuri' },
  206: { state: 'Uttar Pradesh', district: 'Etawah' },
  207: { state: 'Uttar Pradesh', district: 'Etah' },
  208: { state: 'Uttar Pradesh', district: 'Kanpur Nagar' },
  209: { state: 'Uttar Pradesh', district: 'Kanpur Nagar' },
  210: { state: 'Uttar Pradesh', district: 'Banda' },
  211: { state: 'Uttar Pradesh', district: 'Prayagraj' },
  212: { state: 'Uttar Pradesh', district: 'Prayagraj' },
  213: { state: 'Uttar Pradesh', district: 'Prayagraj' },
  214: { state: 'Uttar Pradesh', district: 'Fatehpur' },
  215: { state: 'Uttar Pradesh', district: 'Rae Bareli' },
  216: { state: 'Uttar Pradesh', district: 'Sitapur' },
  221: { state: 'Uttar Pradesh', district: 'Varanasi' },
  222: { state: 'Uttar Pradesh', district: 'Jaunpur' },
  223: { state: 'Uttar Pradesh', district: 'Azamgarh' },
  224: { state: 'Uttar Pradesh', district: 'Lucknow' },
  225: { state: 'Uttar Pradesh', district: 'Lucknow' },
  226: { state: 'Uttar Pradesh', district: 'Lucknow' },
  227: { state: 'Uttar Pradesh', district: 'Lucknow' },
  228: { state: 'Uttar Pradesh', district: 'Sultanpur' },
  229: { state: 'Uttar Pradesh', district: 'Rae Bareli' },
  231: { state: 'Uttar Pradesh', district: 'Mirzapur' },
  232: { state: 'Uttar Pradesh', district: 'Varanasi' },
  233: { state: 'Uttar Pradesh', district: 'Ghazipur' },
  241: { state: 'Uttar Pradesh', district: 'Hardoi' },
  242: { state: 'Uttar Pradesh', district: 'Shahjahanpur' },
  243: { state: 'Uttar Pradesh', district: 'Bareilly' },
  244: { state: 'Uttar Pradesh', district: 'Moradabad' },
  245: { state: 'Uttar Pradesh', district: 'Hapur' },
  246: { state: 'Uttarakhand', district: 'Pauri Garhwal' },
  247: { state: 'Uttar Pradesh', district: 'Saharanpur' },
  248: { state: 'Uttarakhand', district: 'Dehradun' },
  249: { state: 'Uttarakhand', district: 'Tehri Garhwal' },
  250: { state: 'Uttar Pradesh', district: 'Meerut' },
  251: { state: 'Uttar Pradesh', district: 'Meerut' },
  261: { state: 'Uttar Pradesh', district: 'Sitapur' },
  262: { state: 'Uttar Pradesh', district: 'Pilibhit' },
  263: { state: 'Uttarakhand', district: 'Nainital' },
  264: { state: 'Uttarakhand', district: 'Nainital' },
  271: { state: 'Uttar Pradesh', district: 'Gonda' },
  272: { state: 'Uttar Pradesh', district: 'Basti' },
  273: { state: 'Uttar Pradesh', district: 'Gorakhpur' },
  274: { state: 'Uttar Pradesh', district: 'Deoria' },
  275: { state: 'Uttar Pradesh', district: 'Mau' },
  276: { state: 'Uttar Pradesh', district: 'Azamgarh' },
  281: { state: 'Uttar Pradesh', district: 'Mathura' },
  282: { state: 'Uttar Pradesh', district: 'Agra' },
  283: { state: 'Uttar Pradesh', district: 'Agra' },
  284: { state: 'Uttar Pradesh', district: 'Jhansi' },
  285: { state: 'Uttar Pradesh', district: 'Jaloun' },

  // ── RAJASTHAN (301–344) ───────────────────────────────────────────────────
  301: { state: 'Rajasthan', district: 'Alwar' },
  302: { state: 'Rajasthan', district: 'Jaipur' },
  303: { state: 'Rajasthan', district: 'Jaipur' },
  304: { state: 'Rajasthan', district: 'Tonk' },
  305: { state: 'Rajasthan', district: 'Ajmer' },
  306: { state: 'Rajasthan', district: 'Pali' },
  307: { state: 'Rajasthan', district: 'Sirohi' },
  311: { state: 'Rajasthan', district: 'Bhilwara' },
  312: { state: 'Rajasthan', district: 'Chittorgarh' },
  313: { state: 'Rajasthan', district: 'Udaipur' },
  314: { state: 'Rajasthan', district: 'Dungarpur' },
  321: { state: 'Rajasthan', district: 'Bharatpur' },
  322: { state: 'Rajasthan', district: 'Sawai Madhopur' },
  323: { state: 'Rajasthan', district: 'Bundi' },
  324: { state: 'Rajasthan', district: 'Kota' },
  325: { state: 'Rajasthan', district: 'Kota' },
  326: { state: 'Rajasthan', district: 'Jhalawar' },
  327: { state: 'Rajasthan', district: 'Banswara' },
  328: { state: 'Rajasthan', district: 'Dholpur' },
  331: { state: 'Rajasthan', district: 'Churu' },
  332: { state: 'Rajasthan', district: 'Sikar' },
  333: { state: 'Rajasthan', district: 'Jhunjhunu' },
  334: { state: 'Rajasthan', district: 'Bikaner' },
  335: { state: 'Rajasthan', district: 'Ganganagar' },
  341: { state: 'Rajasthan', district: 'Nagaur' },
  342: { state: 'Rajasthan', district: 'Jodhpur' },
  343: { state: 'Rajasthan', district: 'Jalor' },
  344: { state: 'Rajasthan', district: 'Barmer' },

  // ── GUJARAT (360–396) ─────────────────────────────────────────────────────
  360: { state: 'Gujarat', district: 'Rajkot' },
  361: { state: 'Gujarat', district: 'Jamnagar' },
  362: { state: 'Gujarat', district: 'Junagadh' },
  363: { state: 'Gujarat', district: 'Surendranagar' },
  364: { state: 'Gujarat', district: 'Bhavnagar' },
  365: { state: 'Gujarat', district: 'Amreli' },
  370: { state: 'Gujarat', district: 'Kutch' },
  380: { state: 'Gujarat', district: 'Ahmedabad' },
  381: { state: 'Gujarat', district: 'Ahmedabad' },
  382: { state: 'Gujarat', district: 'Gandhinagar' },
  383: { state: 'Gujarat', district: 'Sabarkantha' },
  384: { state: 'Gujarat', district: 'Mehsana' },
  385: { state: 'Gujarat', district: 'Banaskantha' },
  387: { state: 'Gujarat', district: 'Anand' },
  388: { state: 'Gujarat', district: 'Anand' },
  390: { state: 'Gujarat', district: 'Vadodara' },
  391: { state: 'Gujarat', district: 'Vadodara' },
  392: { state: 'Gujarat', district: 'Bharuch' },
  393: { state: 'Gujarat', district: 'Bharuch' },
  394: { state: 'Gujarat', district: 'Surat' },
  395: { state: 'Gujarat', district: 'Surat' },
  396: { state: 'Gujarat', district: 'Navsari' },

  // ── MAHARASHTRA (400–445) ─────────────────────────────────────────────────
  400: { state: 'Maharashtra', district: 'Mumbai' },
  401: { state: 'Maharashtra', district: 'Mumbai Suburban' },
  402: { state: 'Maharashtra', district: 'Raigad' },
  403: { state: 'Goa', district: 'North Goa' },
  404: { state: 'Maharashtra', district: 'Ahmednagar' },
  405: { state: 'Maharashtra', district: 'Ahmednagar' },
  406: { state: 'Maharashtra', district: 'Latur' },
  410: { state: 'Maharashtra', district: 'Pune' },
  411: { state: 'Maharashtra', district: 'Pune' },
  412: { state: 'Maharashtra', district: 'Pune' },
  413: { state: 'Maharashtra', district: 'Solapur' },
  414: { state: 'Maharashtra', district: 'Ahmednagar' },
  415: { state: 'Maharashtra', district: 'Satara' },
  416: { state: 'Maharashtra', district: 'Kolhapur' },
  417: { state: 'Maharashtra', district: 'Ahmednagar' },
  418: { state: 'Maharashtra', district: 'Washim' },
  419: { state: 'Maharashtra', district: 'Ahmednagar' },
  421: { state: 'Maharashtra', district: 'Thane' },
  422: { state: 'Maharashtra', district: 'Nashik' },
  423: { state: 'Maharashtra', district: 'Nashik' },
  424: { state: 'Maharashtra', district: 'Dhule' },
  425: { state: 'Maharashtra', district: 'Jalgaon' },
  426: { state: 'Maharashtra', district: 'Buldhana' },
  427: { state: 'Maharashtra', district: 'Akola' },
  428: { state: 'Maharashtra', district: 'Washim' },
  431: { state: 'Maharashtra', district: 'Aurangabad' },
  432: { state: 'Maharashtra', district: 'Aurangabad' },
  433: { state: 'Maharashtra', district: 'Aurangabad' },
  434: { state: 'Maharashtra', district: 'Buldhana' },
  435: { state: 'Maharashtra', district: 'Yavatmal' },
  436: { state: 'Maharashtra', district: 'Hingoli' },
  440: { state: 'Maharashtra', district: 'Nagpur' },
  441: { state: 'Maharashtra', district: 'Nagpur' },
  442: { state: 'Maharashtra', district: 'Wardha' },
  443: { state: 'Maharashtra', district: 'Buldhana' },
  444: { state: 'Maharashtra', district: 'Amravati' },
  445: { state: 'Maharashtra', district: 'Yavatmal' },

  // ── MADHYA PRADESH (450–488) ──────────────────────────────────────────────
  450: { state: 'Madhya Pradesh', district: 'Dewas' },
  451: { state: 'Madhya Pradesh', district: 'Khargone' },
  452: { state: 'Madhya Pradesh', district: 'Indore' },
  453: { state: 'Madhya Pradesh', district: 'Indore' },
  454: { state: 'Madhya Pradesh', district: 'Dhar' },
  455: { state: 'Madhya Pradesh', district: 'Dewas' },
  456: { state: 'Madhya Pradesh', district: 'Ujjain' },
  457: { state: 'Madhya Pradesh', district: 'Ratlam' },
  458: { state: 'Madhya Pradesh', district: 'Neemuch' },
  460: { state: 'Madhya Pradesh', district: 'Betul' },
  461: { state: 'Madhya Pradesh', district: 'Hoshangabad' },
  462: { state: 'Madhya Pradesh', district: 'Bhopal' },
  463: { state: 'Madhya Pradesh', district: 'Bhopal' },
  464: { state: 'Madhya Pradesh', district: 'Vidisha' },
  465: { state: 'Madhya Pradesh', district: 'Shajapur' },
  466: { state: 'Madhya Pradesh', district: 'Sehore' },
  470: { state: 'Madhya Pradesh', district: 'Sagar' },
  471: { state: 'Madhya Pradesh', district: 'Chhatarpur' },
  472: { state: 'Madhya Pradesh', district: 'Tikamgarh' },
  473: { state: 'Madhya Pradesh', district: 'Guna' },
  474: { state: 'Madhya Pradesh', district: 'Gwalior' },
  475: { state: 'Madhya Pradesh', district: 'Gwalior' },
  476: { state: 'Madhya Pradesh', district: 'Morena' },
  477: { state: 'Madhya Pradesh', district: 'Bhind' },
  480: { state: 'Madhya Pradesh', district: 'Chhindwara' },
  481: { state: 'Madhya Pradesh', district: 'Balaghat' },
  482: { state: 'Madhya Pradesh', district: 'Jabalpur' },
  483: { state: 'Madhya Pradesh', district: 'Jabalpur' },
  484: { state: 'Madhya Pradesh', district: 'Anuppur' },
  485: { state: 'Madhya Pradesh', district: 'Satna' },
  486: { state: 'Madhya Pradesh', district: 'Rewa' },
  487: { state: 'Madhya Pradesh', district: 'Narsinghpur' },
  488: { state: 'Madhya Pradesh', district: 'Panna' },

  // ── CHHATTISGARH (490–497) ────────────────────────────────────────────────
  490: { state: 'Chhattisgarh', district: 'Durg' },
  491: { state: 'Chhattisgarh', district: 'Durg' },
  492: { state: 'Chhattisgarh', district: 'Raipur' },
  493: { state: 'Chhattisgarh', district: 'Raipur' },
  494: { state: 'Chhattisgarh', district: 'Bastar' },
  495: { state: 'Chhattisgarh', district: 'Bilaspur' },
  496: { state: 'Chhattisgarh', district: 'Raigarh' },
  497: { state: 'Chhattisgarh', district: 'Surguja' },

  // ── ANDHRA PRADESH (500–535) ──────────────────────────────────────────────
  500: { state: 'Telangana', district: 'Hyderabad' },
  501: { state: 'Telangana', district: 'Ranga Reddy' },
  502: { state: 'Telangana', district: 'Medak' },
  503: { state: 'Telangana', district: 'Nizamabad' },
  504: { state: 'Telangana', district: 'Adilabad' },
  505: { state: 'Telangana', district: 'Karimnagar' },
  506: { state: 'Telangana', district: 'Warangal' },
  507: { state: 'Telangana', district: 'Khammam' },
  508: { state: 'Telangana', district: 'Nalgonda' },
  509: { state: 'Telangana', district: 'Mahabubnagar' },
  515: { state: 'Andhra Pradesh', district: 'Anantapur' },
  516: { state: 'Andhra Pradesh', district: 'Kadapa' },
  517: { state: 'Andhra Pradesh', district: 'Chittoor' },
  518: { state: 'Andhra Pradesh', district: 'Kurnool' },
  519: { state: 'Andhra Pradesh', district: 'Kurnool' },
  520: { state: 'Andhra Pradesh', district: 'Krishna' },
  521: { state: 'Andhra Pradesh', district: 'Krishna' },
  522: { state: 'Andhra Pradesh', district: 'Guntur' },
  523: { state: 'Andhra Pradesh', district: 'Prakasam' },
  524: { state: 'Andhra Pradesh', district: 'Nellore' },
  530: { state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  531: { state: 'Andhra Pradesh', district: 'Visakhapatnam' },
  532: { state: 'Andhra Pradesh', district: 'Srikakulam' },
  533: { state: 'Andhra Pradesh', district: 'East Godavari' },
  534: { state: 'Andhra Pradesh', district: 'West Godavari' },
  535: { state: 'Andhra Pradesh', district: 'Vizianagaram' },

  // ── KARNATAKA (560–591) ───────────────────────────────────────────────────
  560: { state: 'Karnataka', district: 'Bangalore Urban' },
  561: { state: 'Karnataka', district: 'Bangalore Rural' },
  562: { state: 'Karnataka', district: 'Bangalore Rural' },
  563: { state: 'Karnataka', district: 'Kolar' },
  564: { state: 'Karnataka', district: 'Davangere' },
  565: { state: 'Karnataka', district: 'Raichur' },
  566: { state: 'Karnataka', district: 'Koppal' },
  570: { state: 'Karnataka', district: 'Mysore' },
  571: { state: 'Karnataka', district: 'Mysore' },
  572: { state: 'Karnataka', district: 'Tumkur' },
  573: { state: 'Karnataka', district: 'Hassan' },
  574: { state: 'Karnataka', district: 'Dakshina Kannada' },
  575: { state: 'Karnataka', district: 'Dakshina Kannada' },
  576: { state: 'Karnataka', district: 'Udupi' },
  577: { state: 'Karnataka', district: 'Shimoga' },
  578: { state: 'Karnataka', district: 'Chikmagalur' },
  580: { state: 'Karnataka', district: 'Dharwad' },
  581: { state: 'Karnataka', district: 'Dharwad' },
  582: { state: 'Karnataka', district: 'Gadag' },
  583: { state: 'Karnataka', district: 'Bellary' },
  584: { state: 'Karnataka', district: 'Raichur' },
  585: { state: 'Karnataka', district: 'Gulbarga' },
  586: { state: 'Karnataka', district: 'Bijapur' },
  587: { state: 'Karnataka', district: 'Bijapur' },
  590: { state: 'Karnataka', district: 'Belgaum' },
  591: { state: 'Karnataka', district: 'Belgaum' },

  // ── TAMIL NADU (600–643) ──────────────────────────────────────────────────
  600: { state: 'Tamil Nadu', district: 'Chennai' },
  601: { state: 'Tamil Nadu', district: 'Kanchipuram' },
  602: { state: 'Tamil Nadu', district: 'Tiruvallur' },
  603: { state: 'Tamil Nadu', district: 'Kanchipuram' },
  604: { state: 'Tamil Nadu', district: 'Villupuram' },
  605: { state: 'Tamil Nadu', district: 'Puducherry' },
  606: { state: 'Tamil Nadu', district: 'Villupuram' },
  607: { state: 'Tamil Nadu', district: 'Cuddalore' },
  608: { state: 'Tamil Nadu', district: 'Cuddalore' },
  609: { state: 'Tamil Nadu', district: 'Nagapattinam' },
  610: { state: 'Tamil Nadu', district: 'Thanjavur' },
  611: { state: 'Tamil Nadu', district: 'Nagapattinam' },
  612: { state: 'Tamil Nadu', district: 'Thanjavur' },
  613: { state: 'Tamil Nadu', district: 'Thanjavur' },
  614: { state: 'Tamil Nadu', district: 'Tiruvarur' },
  620: { state: 'Tamil Nadu', district: 'Tiruchirappalli' },
  621: { state: 'Tamil Nadu', district: 'Perambalur' },
  622: { state: 'Tamil Nadu', district: 'Pudukkottai' },
  623: { state: 'Tamil Nadu', district: 'Ramanathapuram' },
  624: { state: 'Tamil Nadu', district: 'Dindigul' },
  625: { state: 'Tamil Nadu', district: 'Madurai' },
  626: { state: 'Tamil Nadu', district: 'Virudhunagar' },
  627: { state: 'Tamil Nadu', district: 'Tirunelveli' },
  628: { state: 'Tamil Nadu', district: 'Tirunelveli' },
  629: { state: 'Tamil Nadu', district: 'Kanyakumari' },
  630: { state: 'Tamil Nadu', district: 'Sivaganga' },
  631: { state: 'Tamil Nadu', district: 'Vellore' },
  632: { state: 'Tamil Nadu', district: 'Vellore' },
  633: { state: 'Tamil Nadu', district: 'Villupuram' },
  634: { state: 'Tamil Nadu', district: 'Kanchipuram' },
  635: { state: 'Tamil Nadu', district: 'Krishnagiri' },
  636: { state: 'Tamil Nadu', district: 'Salem' },
  637: { state: 'Tamil Nadu', district: 'Namakkal' },
  638: { state: 'Tamil Nadu', district: 'Erode' },
  639: { state: 'Tamil Nadu', district: 'Karur' },
  641: { state: 'Tamil Nadu', district: 'Coimbatore' },
  642: { state: 'Tamil Nadu', district: 'Coimbatore' },
  643: { state: 'Tamil Nadu', district: 'Nilgiris' },

  // ── KERALA (670–695) ──────────────────────────────────────────────────────
  670: { state: 'Kerala', district: 'Kannur' },
  671: { state: 'Kerala', district: 'Kasaragod' },
  672: { state: 'Kerala', district: 'Kannur' },
  673: { state: 'Kerala', district: 'Kozhikode' },
  674: { state: 'Kerala', district: 'Malappuram' },
  675: { state: 'Kerala', district: 'Malappuram' },
  676: { state: 'Kerala', district: 'Malappuram' },
  677: { state: 'Kerala', district: 'Palakkad' },
  678: { state: 'Kerala', district: 'Palakkad' },
  679: { state: 'Kerala', district: 'Palakkad' },
  680: { state: 'Kerala', district: 'Thrissur' },
  681: { state: 'Kerala', district: 'Ernakulam' },
  682: { state: 'Kerala', district: 'Ernakulam' },
  683: { state: 'Kerala', district: 'Ernakulam' },
  684: { state: 'Kerala', district: 'Alappuzha' },
  685: { state: 'Kerala', district: 'Idukki' },
  686: { state: 'Kerala', district: 'Kottayam' },
  687: { state: 'Kerala', district: 'Kottayam' },
  688: { state: 'Kerala', district: 'Alappuzha' },
  689: { state: 'Kerala', district: 'Pathanamthitta' },
  690: { state: 'Kerala', district: 'Kollam' },
  691: { state: 'Kerala', district: 'Kollam' },
  692: { state: 'Kerala', district: 'Kollam' },
  695: { state: 'Kerala', district: 'Thiruvananthapuram' },

  // ── WEST BENGAL (700–743) ─────────────────────────────────────────────────
  700: { state: 'West Bengal', district: 'Kolkata' },
  711: { state: 'West Bengal', district: 'Howrah' },
  712: { state: 'West Bengal', district: 'Hooghly' },
  713: { state: 'West Bengal', district: 'Hooghly' },
  721: { state: 'West Bengal', district: 'Paschim Medinipur' },
  722: { state: 'West Bengal', district: 'Bankura' },
  723: { state: 'West Bengal', district: 'Purulia' },
  731: { state: 'West Bengal', district: 'Birbhum' },
  732: { state: 'West Bengal', district: 'Murshidabad' },
  733: { state: 'West Bengal', district: 'Malda' },
  734: { state: 'West Bengal', district: 'Darjeeling' },
  735: { state: 'West Bengal', district: 'Jalpaiguri' },
  736: { state: 'West Bengal', district: 'Cooch Behar' },
  741: { state: 'West Bengal', district: 'Nadia' },
  742: { state: 'West Bengal', district: 'Murshidabad' },
  743: { state: 'West Bengal', district: 'North 24 Parganas' },

  // ── ODISHA (751–770) ──────────────────────────────────────────────────────
  751: { state: 'Odisha', district: 'Khorda' },
  752: { state: 'Odisha', district: 'Nayagarh' },
  753: { state: 'Odisha', district: 'Cuttack' },
  754: { state: 'Odisha', district: 'Jagatsinghpur' },
  755: { state: 'Odisha', district: 'Jajpur' },
  756: { state: 'Odisha', district: 'Bhadrak' },
  757: { state: 'Odisha', district: 'Mayurbhanj' },
  758: { state: 'Odisha', district: 'Keonjhar' },
  759: { state: 'Odisha', district: 'Dhenkanal' },
  760: { state: 'Odisha', district: 'Ganjam' },
  761: { state: 'Odisha', district: 'Ganjam' },
  762: { state: 'Odisha', district: 'Kandhamal' },
  763: { state: 'Odisha', district: 'Koraput' },
  764: { state: 'Odisha', district: 'Nabarangapur' },
  765: { state: 'Odisha', district: 'Rayagada' },
  766: { state: 'Odisha', district: 'Kalahandi' },
  767: { state: 'Odisha', district: 'Bargarh' },
  768: { state: 'Odisha', district: 'Sambalpur' },
  769: { state: 'Odisha', district: 'Sundargarh' },
  770: { state: 'Odisha', district: 'Sundargarh' },

  // ── ASSAM & NORTHEAST (781–799) ───────────────────────────────────────────
  781: { state: 'Assam', district: 'Kamrup' },
  782: { state: 'Assam', district: 'Nagaon' },
  783: { state: 'Assam', district: 'Dhubri' },
  784: { state: 'Assam', district: 'Sonitpur' },
  785: { state: 'Assam', district: 'Jorhat' },
  786: { state: 'Assam', district: 'Dibrugarh' },
  787: { state: 'Arunachal Pradesh', district: 'Papum Pare' },
  788: { state: 'Assam', district: 'Cachar' },
  790: { state: 'Arunachal Pradesh', district: 'East Siang' },
  791: { state: 'Arunachal Pradesh', district: 'West Siang' },
  792: { state: 'Arunachal Pradesh', district: 'Lohit' },
  793: { state: 'Meghalaya', district: 'East Khasi Hills' },
  794: { state: 'Meghalaya', district: 'West Garo Hills' },
  795: { state: 'Manipur', district: 'Imphal East' },
  796: { state: 'Mizoram', district: 'Aizawl' },
  797: { state: 'Nagaland', district: 'Kohima' },
  798: { state: 'Nagaland', district: 'Mokokchung' },
  799: { state: 'Tripura', district: 'West Tripura' },

  // ── BIHAR (800–845) ───────────────────────────────────────────────────────
  800: { state: 'Bihar', district: 'Patna' },
  801: { state: 'Bihar', district: 'Patna' },
  802: { state: 'Bihar', district: 'Bhojpur' },
  803: { state: 'Bihar', district: 'Nalanda' },
  804: { state: 'Bihar', district: 'Nalanda' },
  805: { state: 'Bihar', district: 'Gaya' },
  811: { state: 'Bihar', district: 'Munger' },
  812: { state: 'Bihar', district: 'Munger' },
  813: { state: 'Bihar', district: 'Bhagalpur' },
  814: { state: 'Bihar', district: 'Deoghar' },
  815: { state: 'Jharkhand', district: 'Giridih' },
  816: { state: 'Jharkhand', district: 'Pakur' },
  821: { state: 'Bihar', district: 'Rohtas' },
  822: { state: 'Jharkhand', district: 'Palamu' },
  823: { state: 'Bihar', district: 'Gaya' },
  824: { state: 'Bihar', district: 'Aurangabad' },
  825: { state: 'Jharkhand', district: 'Hazaribagh' },
  826: { state: 'Jharkhand', district: 'Dhanbad' },
  827: { state: 'Jharkhand', district: 'Bokaro' },
  828: { state: 'Jharkhand', district: 'Dhanbad' },
  829: { state: 'Jharkhand', district: 'Ramgarh' },
  831: { state: 'Jharkhand', district: 'East Singhbhum' },
  832: { state: 'Jharkhand', district: 'East Singhbhum' },
  833: { state: 'Jharkhand', district: 'West Singhbhum' },
  834: { state: 'Jharkhand', district: 'Ranchi' },
  835: { state: 'Jharkhand', district: 'Ranchi' },
  841: { state: 'Bihar', district: 'Saran' },
  842: { state: 'Bihar', district: 'Muzaffarpur' },
  843: { state: 'Bihar', district: 'Muzaffarpur' },
  844: { state: 'Bihar', district: 'Vaishali' },
  845: { state: 'Bihar', district: 'Champaran' },

  // ── SIKKIM (737) ──────────────────────────────────────────────────────────
  737: { state: 'Sikkim', district: 'East Sikkim' },

  // ── ANDAMAN & NICOBAR (744) ───────────────────────────────────────────────
  744: { state: 'Andaman and Nicobar', district: 'South Andaman' },

  // ── LAKSHADWEEP (682 conflicts — use 673 area) ────────────────────────────
  // 682004 is Lakshadweep but we handle it via no-COD list
}

// ─────────────────────────────────────────────────────────────────────────────
// Metro districts for faster delivery estimate
// ─────────────────────────────────────────────────────────────────────────────
const METRO_DISTRICTS = new Set([
  'Mumbai', 'New Delhi', 'Bangalore Urban', 'Chennai',
  'Hyderabad', 'Kolkata', 'Pune', 'Ahmedabad',
  'Surat', 'Jaipur', 'Ludhiana', 'Nagpur',
])

const NO_COD_STATES = new Set(['Andaman and Nicobar', 'Lakshadweep'])

// ─────────────────────────────────────────────────────────────────────────────
// Main lookup function
// ─────────────────────────────────────────────────────────────────────────────
export function lookupPincode(pincode) {
  const str    = String(pincode).trim()
  const prefix = parseInt(str.slice(0, 3))
  const entry  = PINCODE_DB[prefix]

  if (!entry) return null   // unknown pincode prefix

  const { state, district } = entry
  const isMetro      = METRO_DISTRICTS.has(district)
  const deliveryDays = isMetro ? 2 : 4
  const deliveryDate = new Date(Date.now() + deliveryDays * 86400000)
    .toLocaleDateString('en-IN', { weekday: 'short', month: 'short', day: 'numeric' })
  const codAvailable = !NO_COD_STATES.has(state)

  return {
    available: true,
    pincode:   str,
    state,
    district,
    division:      district,
    deliveryDate,
    deliveryDays,
    codAvailable,
    areas:     [],           // no area list without external API — that's fine
    message:   `Delivery available in ${district}, ${state}`,
  }
}